/**
 * ISO 3166-1 alpha-2 → ISO 4217 currency.
 * Covers GCC, common e-commerce destinations, and major markets.
 * Unknown codes return null (caller shows warning, no silent FX).
 */
const COUNTRY_TO_CURRENCY: Record<string, string> = {
  SA: "SAR",
  AE: "AED",
  KW: "KWD",
  BH: "BHD",
  QA: "QAR",
  OM: "OMR",
  GB: "GBP",
  US: "USD",
  CA: "CAD",
  AU: "AUD",
  NZ: "NZD",
  JP: "JPY",
  CN: "CNY",
  HK: "HKD",
  SG: "SGD",
  MY: "MYR",
  TH: "THB",
  ID: "IDR",
  PH: "PHP",
  VN: "VND",
  IN: "INR",
  PK: "PKR",
  BD: "BDT",
  LK: "LKR",
  NP: "NPR",
  EG: "EGP",
  MA: "MAD",
  TN: "TND",
  DZ: "DZD",
  ZA: "ZAR",
  NG: "NGN",
  KE: "KES",
  GH: "GHS",
  TR: "TRY",
  IL: "ILS",
  JO: "JOD",
  LB: "LBP",
  IQ: "IQD",
  YE: "YER",
  DE: "EUR",
  FR: "EUR",
  IT: "EUR",
  ES: "EUR",
  NL: "EUR",
  BE: "EUR",
  AT: "EUR",
  PT: "EUR",
  IE: "EUR",
  GR: "EUR",
  FI: "EUR",
  LU: "EUR",
  CY: "EUR",
  EE: "EUR",
  LV: "EUR",
  LT: "EUR",
  SK: "EUR",
  SI: "EUR",
  MT: "EUR",
  HR: "EUR",
  CH: "CHF",
  NO: "NOK",
  SE: "SEK",
  DK: "DKK",
  IS: "ISK",
  PL: "PLN",
  CZ: "CZK",
  HU: "HUF",
  RO: "RON",
  BG: "BGN",
  RS: "RSD",
  UA: "UAH",
  RU: "RUB",
  BY: "BYN",
  MX: "MXN",
  BR: "BRL",
  AR: "ARS",
  CL: "CLP",
  CO: "COP",
  PE: "PEN",
  KR: "KRW",
  TW: "TWD",
  GE: "GEL",
  AM: "AMD",
  AZ: "AZN",
  KZ: "KZT",
  UZ: "UZS",
};

export function getCurrencyForCountry(
  countryCode: string | null | undefined,
): { currency: string } | { currency: null; reason: "unknown_country" } {
  if (!countryCode) return { currency: null, reason: "unknown_country" };
  const cc = countryCode.trim().toUpperCase();
  const currency = COUNTRY_TO_CURRENCY[cc];
  if (!currency) return { currency: null, reason: "unknown_country" };
  return { currency };
}
